name: Flutter Build (v4 - Auto Android Create)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # 🔹 Generate android/ ios/ folder if missing
      - name: Create Android & iOS folder
        run: flutter create .

      # 🔹 Patch Android app name
      - name: Patch Android App Name
        run: |
          sed -i 's/android:label="[^"]*"/android:label="Swoofi Support App"/g' android/app/src/main/AndroidManifest.xml

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK (v4)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
